# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mis-knaumenko/mis/Style transfer/MapTransferQT5/test/StartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(452, 300)
        self.pushButton = QtWidgets.QPushButton(StartWindow)
        self.pushButton.setGeometry(QtCore.QRect(40, 250, 80, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(StartWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 250, 80, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(StartWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 60, 41, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget = QtWidgets.QWidget(StartWindow)
        self.widget.setGeometry(QtCore.QRect(30, 30, 311, 141))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "Choose image"))
        self.pushButton.setText(_translate("StartWindow", "Quit"))
        self.pushButton_2.setText(_translate("StartWindow", "Run"))
        self.pushButton_3.setText(_translate("StartWindow", "..."))
        self.label.setText(_translate("StartWindow", "Path:"))
        self.label_2.setText(_translate("StartWindow", "Type:"))
